/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guessinggame;

import java.io.IOException;
import java.util.Random;

/**
 *
 * @author ltmer
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    Deck d;
    int com;
    int pScore;
    int cScore;
    int round;
    
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPlayerText = new javax.swing.JTextField();
        jComText = new javax.swing.JTextField();
        jGuess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCard = new javax.swing.JLabel();
        jResult = new javax.swing.JLabel();
        jRound = new javax.swing.JLabel();
        jCScore = new javax.swing.JLabel();
        jPScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPlayerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 98, 142, -1));

        jComText.setEditable(false);
        jPanel1.add(jComText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 187, 142, -1));

        jGuess.setText("Start Game!");
        jGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuessActionPerformed(evt);
            }
        });
        jPanel1.add(jGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 263, 142, 80));

        jLabel1.setText("Player Guess:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 67, -1, -1));

        jLabel2.setText("Computer Guess:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 156, -1, -1));

        jCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        jPanel1.add(jCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 156, -1, -1));

        jResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jResult.setText("Good Luck!");
        jPanel1.add(jResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 240, 30));

        jRound.setText("Round:");
        jPanel1.add(jRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jCScore.setText("Computer Score:");
        jPanel1.add(jCScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jPScore.setText("Player Score:");
        jPanel1.add(jPScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuessActionPerformed
        
        if(jGuess.getText() == "Next Round!" || jGuess.getText() == "Start Game!"){
            //Checks if new game and does setup
            if(jGuess.getText() == "Start Game!"){
                d = new Deck();
                d.shuffle();
                round = 0;
                pScore = 0;
                cScore = 0;
                jPScore.setText("Player Score: " + pScore);
                jCScore.setText("Computer Score: " + cScore);
                jResult.setText("Good Luck!");
            }
            //Cleanup
            jGuess.setText("Guess!");
            jPlayerText.setText("");
            jCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png")));
            round++;
            jRound.setText("Round: " + round);
            
            //Getting and displaying computer guess
            Random r = new Random();
            com = r.nextInt(13)+1;
            jComText.setText(com+"");
            return;
        }
        
        //Getting users guess and checking if number
        int guess; //= Integer.parseInt(jPlayerText.getText());
        try {
            guess = Integer.parseInt(jPlayerText.getText());
        } catch (NumberFormatException e) {
            jResult.setText("Only input numbers!!!!");
            return;
        }

        
        //Getting card
        Card c1 = d.getTopCard();
        int card = c1.getValue();
        
        //Checking who's closer
        if (Math.abs(card-com)<Math.abs(card-guess)) {
            jResult.setText("Computer Wins This Round!");
            cScore++;
        } else if(Math.abs(card-com)>Math.abs(card-guess)){
            jResult.setText("Player Wins This Round!");
            pScore++;
        }else{
            jResult.setText("TIE");
            
        }
        
        //Post round setup
        jPScore.setText("Player Score: " + pScore);
        jCScore.setText("Computer Score: " + cScore);
        jCard.setIcon(new javax.swing.ImageIcon(getClass().getResource(c1.getImage())));
        jGuess.setText("Next Round!");
         
        //Checking for game completion, and doing post game setup
        if(round>=10){
            if(pScore>cScore){
                jResult.setText("PLAYER WINS THE GAME!!!");
                jGuess.setText("Start Game!");
            }else if(cScore>pScore){
                jResult.setText("COMPUTER WINS THE GAME!!!");
                jGuess.setText("Start Game!");
            }else{
                jResult.setText("TIE GAME!!!");
                jGuess.setText("Start Game!");
            }
        }
    }//GEN-LAST:event_jGuessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCScore;
    private javax.swing.JLabel jCard;
    private javax.swing.JTextField jComText;
    private javax.swing.JButton jGuess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jPScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPlayerText;
    private javax.swing.JLabel jResult;
    private javax.swing.JLabel jRound;
    // End of variables declaration//GEN-END:variables
}
